export const emojis = [
  { emoji: "😀", name: "Smile" },
  { emoji: "🐶", name: "Dog" },
  { emoji: "🌮", name: "Taco" },
  { emoji: "🚀", name: "Rocket" },
  { emoji: "🌺", name: "Flower" },
  { emoji: "🍕", name: "Pizza" },
  { emoji: "📚", name: "Book" },
  { emoji: "🎉", name: "Party" },
  { emoji: "🌞", name: "Sun" },
  { emoji: "🌍", name: "Earth" },
  { emoji: "🍎", name: "Apple" },
  { emoji: "🚲", name: "Bicycle" },
  { emoji: "🎸", name: "Guitar" },
  { emoji: "📷", name: "Camera" },
  { emoji: "⌚", name: "Watch" },
  { emoji: "🍔", name: "Hamburger" },
  { emoji: "🌳", name: "Tree" },
  { emoji: "🔑", name: "Key" },
  { emoji: "🎈", name: "Balloon" },
  { emoji: "🌈", name: "Rainbow" },
];
